config/routes.rb
Rails.application.routes.draw do
root "recipes#index"
resources :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :all_recipes, only: [:index, :create, :update, :destroy]
    before_action :set_recipe, only: [:edit, :update, :destroy]
    respond_to :html, :js
    def index
    end
    def destroy
        @recipe.destroy
    end
    def new
        @recipe = Recipe.new
    end
    def create
        @recipe = Recipe.create(recipe_params)
    end
    def update
        @recipe.update_attributes(recipe_params)
    end
    private
    def all_recipes
        @recipes = Recipe.all
    end
    def set_recipe
        @recipe = Recipe.find(params[:id])
    end
    def recipe_params
        params.require(:recipe).permit(:content, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe, remote: true) do |f| %>
    <%= f.input :name, placeholder: "" %>
    <%= f.input :content %>
    <%= f.button :submit%>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="well">
    <h2><%= recipe.name %></h2>
    <p><%= recipe.content %></p>
    <%= link_to edit_recipe_path(recipe), remote: true do %>
        <button class="btn btn-sm btn-info">Edit</button>
    <% end %>
    <%= link_to recipe_path(recipe), remote: true, method: :delete do %>
        <button class="btn btn-sm btn-danger">Delete</button>
    <% end %>
</div>

app/views/recipes/create.js.erb
$("#recipes-holder").html("<%= j (render @recipes) %>");
$("#recipe-form").fadeOut(350);
$("#new-form").fadeIn(350);

app/views/recipes/destroy.js.erb
$("#recipes-holder").html("<%= j (render @recipes) %>");

app/views/recipes/edit.js.erb
$("#recipe-form").html("<%= j (render 'form') %>");

$("#recipe-form").fadeIn(350);

app/views/recipes/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-9 col-md-offset-3">
            <h1>Ajax Recipe Posting App</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3" id="recipe-form">
            <h2>Make a Recipe</h2>
            <%= link_to new_recipe_path, remote: true do %>
            <button class="btn btn-sm btn-primary" id="new-form">New Recipe</button>
            <% end %>
            
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div id="recipes-holder">
                <%= render @recipes %>
            </div>
        </div>
    </div>
</div>

app/views/recipes/new.js.erb
$("#recipe-form").html("<%= j (render 'form') %>");
document.getElementById("recipe-form").reset();
$("#recipe-form").fadeIn(350);

app/views/recipes/update.js.erb
$("#recipes-holder").html("<%= j (render @recipes) %>");
$("#recipe-form").fadeOut(350);